export const SET_COUNTER_NUMBER = 'SET_COUNTER_NUMBER'

export const SET_IDEAS_SINGLE_IDEA = 'SET_IDEAS_SINGLE_IDEA'

export const SET_POSTS_POSTS_LIST = 'SET_POSTS_POSTS_LIST'
export const SET_POSTS_USER = 'SET_POSTS_USER'
export const SET_POSTS_SINGLE_POST = 'SET_POSTS_SINGLE_POST'
export const SET_POSTS_USER_POSTS = 'SET_POSTS_USER_POSTS'
export const SET_POSTS_IS_LOADED_POSTS_LIST = 'SET_POSTS_IS_LOADED_POSTS_LIST'
export const SET_POSTS_IS_LOADED_USER = 'SET_POSTS_IS_LOADED_USER'
export const SET_POSTS_IS_LOADED_SINGLE_POST = 'SET_POSTS_IS_LOADED_SINGLE_POST'
export const SET_POSTS_IS_LOADED_USER_POSTS = 'SET_POSTS_IS_LOADED_USER_POSTS'

