// export const GET_IDEAS_SINGLE_IDEA = 'GET_IDEAS_SINGLE_IDEA'
//
// export const GET_POSTS_POSTS_LIST = 'GET_POSTS_POSTS_LIST'
// export const GET_POSTS_USER = 'GET_POSTS_USER'
// export const GET_POSTS_USER_POSTS = 'GET_POSTS_USER_POSTS'
// export const GET_POSTS_SINGLE_POST = 'GET_POSTS_SINGLE_POST'
// export const CLEAR_POSTS_SINGLE_POST = 'CLEAR_POSTS_SINGLE_POST'